name       : tiled
version    : 1.3.3
release    : 12
source     :
    - https://github.com/bjorn/tiled/archive/v1.3.3.tar.gz : 88b9ca9e45b0235180be55733a4377434969dd6d5947319d83e5cbce8ca868fd
license    :
    - Apache-2.0
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : Tiled is a general purpose tile map editor.
description: |
    Tiled is a general purpose tile map editor.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(python3)
setup      : |
    %patch -p1 < $pkgfiles/0001-Update-default-style-for-better-integration.patch
    %qmake PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
