name       : tiled
version    : 1.0.0
release    : 5
source     :
    - https://github.com/bjorn/tiled/archive/v1.0.0.tar.gz : a5e5f1f3ec9428f124e1fbe65ac3b7ab3c17dc13a3c0d489ff6d356f7f6ad43c
license    :
    - Apache-2.0
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0
component  : multimedia.graphics
summary    : Tiled is a general purpose tile map editor.
description: |
    Tiled is a general purpose tile map editor.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
setup      : |
    %patch -p1 < $pkgfiles/0001-Update-default-style-for-better-integration.patch
    %qmake PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
