name       : tiled
version    : 0.17.1
release    : 2
source     :
    - https://github.com/bjorn/tiled/archive/v0.17.1.tar.gz : 11297f97370df10dd32b24a0c5ce9988b3c1903a13f2be0ebb3c20f49c5e0fb4
license    :
    - Apache-2.0
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0
component  : multimedia.graphics
summary    : Tiled is a general purpose tile map editor.
description: |
    Tiled is a general purpose tile map editor.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
setup      : |
    %qmake PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
